version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    env_file: .env
    volumes:
      - ./.data/mongodbdata:/data/db
    command: mongod --auth
    ports:
      - 27018:27017