from environs import Env


env = Env()
env.read_env()

MONGO_INITDB_ROOT_USERNAME = env.str('MONGO_INITDB_ROOT_USERNAME')
MONGO_INITDB_ROOT_PASSWORD = env.str('MONGO_INITDB_ROOT_PASSWORD')
MONGO_INITDB_DATABASE = env.str('MONGO_INITDB_DATABASE')
MONGO_INITDB_ROOT_PORT = env.str('MONGO_INITDB_ROOT_PORT')
MONGO_INITDB_ROOT_HOST = env.str('MONGO_INITDB_ROOT_HOST')
CORS_ORIGINS = env.list('CORS_ORIGINS', ['*'])

MONGO_URL = f'mongodb://{MONGO_INITDB_ROOT_USERNAME}:{MONGO_INITDB_ROOT_PASSWORD}' \
            f'@{MONGO_INITDB_ROOT_HOST}:{MONGO_INITDB_ROOT_PORT}/{MONGO_INITDB_DATABASE}?authSource=admin'
